# Generated by Django 3.2.25 on 2024-09-05 07:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('park_type_id', models.CharField(max_length=255)),
                ('park_type_desc', models.CharField(max_length=255)),
                ('capacity_of_park', models.PositiveIntegerField()),
                ('working_time', models.CharField(max_length=50)),
                ('county_name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
